In [2]:
#computing neuron
inputs = [1,2,3,4,5]
weights = [0.2, 0.3, -0.8, 0.2, 1.0]
bias = 2

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + inputs[3]*weights[3] + inputs[4]*weights[4] + bias
print(output) 

6.199999999999999


In [3]:
#Coding first layer which consists of 3 neurons
inputs = [1,2,3,4]
weights = [[0.8,1.2,0.4,1.6] , [1.0,1.9,-0.6,1.2], [0.5,-0.6,1.0,0.3]]
biases = [2,3,0.5]

outputs = [
 # Neuron 1:
 inputs[0]*weights[0][0] +
 inputs[1]*weights[0][1] +
 inputs[2]*weights[0][2] +
 inputs[3]*weights[0][3] + biases[0],
 # Neuron 2:
 inputs[0]*weights[1][0] +
 inputs[1]*weights[1][1] +
 inputs[2]*weights[1][2] +
 inputs[3]*weights[1][3] + biases[1],
 # Neuron 3:
 inputs[0]*weights[2][0] +
 inputs[1]*weights[2][1] +
 inputs[2]*weights[2][2] +
 inputs[3]*weights[2][3] + biases[2]]

print(outputs)


[12.8, 10.8, 4.0]


In [ ]:
#Using loops instead 
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

layer_outputs = []




In [4]:
#Single Neuron using Numpy
import numpy as np
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [0.2, 0.8, -0.5, 1.0]
bias = 2.0
outputs = np.dot(weights, inputs) + bias
print(outputs)

4.8


In [5]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)

[4.8   1.21  2.385]


In [7]:
inputs = [[1.0, 2.0, 3.0, 2.5], [2.0, 5.0, -1.0, 2.0], [-1.5, 2.7, 3.3, -0.8]]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

# NOTE: WE CAN'T TRANSPOSE LISTS IN PYTHON, SO WE HAVE THE CONVERT THE WEIGHTS MATRIX INTO AN ARRAY FIRST
outputs = np.dot(inputs, np.array(weights).T) + biases
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [8]:
inputs = [1, 2, 3, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2, 3, 0.5]

layer_outputs = []

for neuron_weights, neuron_bias in zip(weights, biases):
 neuron_output = 0
 for n_input, weight in zip(inputs, neuron_weights):
   neuron_output += n_input*weight 
 neuron_output += neuron_bias 
 layer_outputs.append(neuron_output)
print(layer_outputs)

[4.8, 1.21, 2.385]
